# travis-ci integration for the kiibohd controller firmware
# XXX Using Ubuntu 14.04 Trusty in root mode (we need universe repo, means we can't use container infra yet)

sudo: required
dist: trusty

language:
  - c

os:
  - linux
  - osx

compiler:
  #- clang
  - gcc

# Build Scripts
env:
  # Input Club Keyboard Tests
  - DIR=Keyboards SCRIPT=infinity.bash
  - DIR=Keyboards SCRIPT=infinity_led.bash
  - DIR=Keyboards SCRIPT=ergodox.bash
  - DIR=Keyboards SCRIPT=whitefox.bash
  - DIR=Keyboards SCRIPT=k-type.bash

  # Debug Build Tests
  - DIR=Keyboards/Testing SCRIPT=uartout.bash
  - DIR=Keyboards/Testing SCRIPT=usbmuxuart.bash
  - DIR=Keyboards/Testing SCRIPT=macrotest.bash

  # Bootloader Build Tests
  - DIR=Bootloader/Builds SCRIPT=mk20dx128vlf5.bash
  - DIR=Bootloader/Builds SCRIPT=mk20dx256vlh7.bash

# Exclusions
matrix:
  # TODO - Still some travis clang issues
  allow_failures:
    - compiler: clang
    # Currently there are issues running the macrotest on macOS
    - compiler: gcc
      env: DIR=Keyboards/Testing SCRIPT=macrotest.bash
      os: osx

  exclude:
    # Bootloader doesn't support clang yet
    - compiler: clang
      env: DIR=Bootloader/Builds SCRIPT=mk20dx128vlf5.bash
    - compiler: clang
      env: DIR=Bootloader/Builds SCRIPT=mk20dx256vlh7.bash
    # xcode *and* brew don't support clang ARMCCompiler for arm-none-eabi, sigh useless Apple
    - compiler: clang
      env: DIR=Keyboards SCRIPT=infinity.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards SCRIPT=infinity_led.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards SCRIPT=ergodox.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards SCRIPT=whitefox.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards SCRIPT=k-type.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards/Testing SCRIPT=uartout.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards/Testing SCRIPT=usbmuxuart.bash
      os: osx
    - compiler: clang
      env: DIR=Keyboards/Testing SCRIPT=macrotest.bash
      os: osx
    - compiler: clang
      env: DIR=Bootloader/Builds SCRIPT=mk20dx128vlf5.bash
      os: osx
    - compiler: clang
      env: DIR=Bootloader/Builds SCRIPT=mk20dx256vlh7.bash
      os: osx

# Package Setup
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install software-properties-common -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository universe -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree python3 ctags dfu-util; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CC" == "gcc" ]]; then brew tap Caskroom/cask; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CC" == "gcc" ]]; then brew install Caskroom/cask/gcc-arm-embedded; fi
  # TODO - Add proper gcc for macrotest on macOS

# System setup
install:
  # Info about OS
  - uname -a

  # Pre-clone kll.git to speed-up build
  - git clone https://github.com/kiibohd/kll.git

  # Directory tree to validate kll.git
  - tree

  # Compiler Version
  - ${CC} --version

  # Python Version
  - python --version
  - python3 --version

  # CMake Version
  - cmake --version

# Run test script(s)
script:
  - (cd ${DIR} && COMPILER=${CC} ./${SCRIPT})

# Post test script commands
after_script:
  - tree

